name: Unitary testing
run-name: checking
on:
    branch_protection_rule:
        types: [created, deleted]
jobs:
    print:
        runs-on: ubuntu-lates
        steps:
            - run: echo "no corran esto"