name: Unitary testing
run-name: checking

on:
    pull_request:
        branches: 
        - develop
        types:
        - opened
        - synchronize
        - reopened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
    
  sonarqube:
    runs-on: ubuntu-latest
    services:
      sonar:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: > 
          --health-cmd "curl -s http://localhost:9000/api/system/health | grep -o 'UP' || exit 1" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
      
      - name: sonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


 
